#!/usr/bin/env python3
"""Rewrite README.md's key table from the command registry.

The table lives between two markers (`README_KEYS_START`/`README_KEYS_END` in
kissterm/ui/commands.py) and is generated by `markdown_key_table()`, so a key
change is one edit to `COMMANDS` plus running this script.
`tests/unit/test_docs_keys.py` fails until it has been run.

    .venv/bin/python scripts/sync_docs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from kissterm._isolate import isolate  # noqa: E402

isolate()

from kissterm.ui.commands import (  # noqa: E402
    README_KEYS_END,
    README_KEYS_START,
    markdown_key_table,
)


def synced(text: str) -> str:
    """`text` with the generated table between the markers."""
    start = text.index(README_KEYS_START) + len(README_KEYS_START)
    end = text.index(README_KEYS_END)
    return text[:start] + "\n" + markdown_key_table() + "\n" + text[end:]


def main() -> int:
    readme = ROOT / "README.md"
    before = readme.read_text(encoding="utf-8")
    after = synced(before)
    if after == before:
        print("README.md key table already up to date")
        return 0
    readme.write_text(after, encoding="utf-8")
    print("README.md key table rewritten")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
